version: 2.1

jobs:
  build:
    docker:
      - image: node:14

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Test
          command: npm run test

      - run:
          name: Build
          command: node server.js
